In [2]:
import numpy as np

TASK-1.
Create a NumPy array named prices with these values: [299, 499, 799, 0, 1599, -1, 899]. Print the array and its data type.

In [3]:
prices = np.array([299, 499, 799, 0, 1599, -1, 899])

In [4]:
print("1. Original Prices:")
print(prices)

1. Original Prices:
[ 299  499  799    0 1599   -1  899]


In [5]:
print("Data Type:")
print(prices.dtype)

Data Type:
int64


TASK-2.
Some entries in the prices array are invalid (0 or negative). Replace all values less than or equal to zero with the average of the remaining positive prices.<br><br><em><strong>Hint:</strong> Use boolean indexing and the mean() function.</em>

In [6]:
positive_prices = prices[prices > 0]


In [7]:
average_price = np.mean(positive_prices)

In [8]:
print(" Average of Positive Prices:")
print(average_price)

 Average of Positive Prices:
819.0


In [9]:
cleaned_prices = prices.copy()
cleaned_prices[cleaned_prices <= 0] = average_price

In [10]:
print("Cleaned Prices:")
print(cleaned_prices)

Cleaned Prices:
[ 299  499  799  819 1599  819  899]


TASK-3.
Suppose you have a NumPy array quantities = [2, 1, 3, 4, 2, 1, 5]. Calculate the total bill for each item by multiplying the cleaned prices array with quantities, and print the resulting array.

In [11]:
quantities = np.array([2, 1, 3, 4, 2, 1, 5])


In [12]:
item_bills = cleaned_prices * quantities

In [13]:
print("\n3. Bill for Each Item:")
print(item_bills)


3. Bill for Each Item:
[ 598  499 2397 3276 3198  819 4495]


TASK-4.
Generate and print a summary report: show the minimum, maximum, average, and total of the cleaned prices array, and also the total bill for all items combined.<br><br><em><strong>Hint:</strong> Use NumPy functions like min(), max(), mean(), and sum().</em>

In [14]:
minimum_price = np.min(cleaned_prices)
maximum_price = np.max(cleaned_prices)
average_cleaned_price = np.mean(cleaned_prices)
total_prices = np.sum(cleaned_prices)

In [15]:
total_bill = np.sum(item_bills)


In [16]:
print(" Summary Report")
print("-----------------------")
print("Minimum Price:", minimum_price)
print("Maximum Price:", maximum_price)
print("Average Price:", average_cleaned_price)
print("Total of Cleaned Prices:", total_prices)
print("Total Bill:", total_bill)


 Summary Report
-----------------------
Minimum Price: 299
Maximum Price: 1599
Average Price: 819.0
Total of Cleaned Prices: 5733
Total Bill: 15282


TASK-5.
Use ChatGPT or Copilot to suggest a NumPy function or method that can help you find out how many unique price values are present in your cleaned prices array. Try the suggested method and print the result.

In [17]:
unique_prices = np.unique(cleaned_prices)

In [18]:

print(" Unique Prices:")
print(unique_prices)

 Unique Prices:
[ 299  499  799  819  899 1599]


In [19]:
print("Number of Unique Price Values:")
print(len(unique_prices))

Number of Unique Price Values:
6
