In [1]:
import numpy as np

TASK-1.
Create two NumPy arrays representing the ratings of 5 restaurants on Zomato and Swiggy, then use np.concatenate() to combine them into a single array of 10 ratings and print the result.

In [2]:
zomato_ratings = np.array([4.2, 4.5, 3.8, 4.7, 4.0])
swiggy_ratings = np.array([4.1, 3.9, 4.6, 4.3, 4.8])

In [3]:
zomato_ratings


array([4.2, 4.5, 3.8, 4.7, 4. ])

In [4]:
swiggy_ratings

array([4.1, 3.9, 4.6, 4.3, 4.8])

In [5]:
combined_ratings = np.concatenate((zomato_ratings, swiggy_ratings))

In [6]:
combined_ratings

array([4.2, 4.5, 3.8, 4.7, 4. , 4.1, 3.9, 4.6, 4.3, 4.8])

TASK-2.
Given three arrays representing the number of likes on three different Instagram posts over 7 days, stack them vertically using np.vstack() so that each row represents one post's weekly likes, and print the stacked array.

In [7]:
post1_likes = np.array([100, 120, 150, 180, 200, 220, 250])
post2_likes = np.array([80, 110, 130, 160, 190, 210, 230])
post3_likes = np.array([150, 170, 190, 210, 240, 260, 300])

In [8]:
weekly_likes = np.vstack((post1_likes, post2_likes, post3_likes))

In [10]:

print("2. Instagram Weekly Likes:")
print(weekly_likes)


2. Instagram Weekly Likes:
[[100 120 150 180 200 220 250]
 [ 80 110 130 160 190 210 230]
 [150 170 190 210 240 260 300]]


TASK-3.
You have an array of 12 Flipkart product IDs. Use np.array_split() to divide this array into 5 nearly equal parts, and display each part.<br><br><em><strong>Hint:</strong> Check the shape of each split to confirm the division.</em>

In [11]:
product_ids = np.array([
    101, 102, 103, 104,
    105, 106, 107, 108,
    109, 110, 111, 112
])

In [12]:
product_ids

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])

In [17]:
splits = np.array_split(product_ids, 5)
splits

[array([101, 102, 103]),
 array([104, 105, 106]),
 array([107, 108]),
 array([109, 110]),
 array([111, 112])]

In [16]:
print("3. Flipkart Product ID Splits:")

3. Flipkart Product ID Splits:


In [15]:
for i, part in enumerate(splits, start=1):
    print("Part", i, ":", part)
    print("Shape:", part.shape)

Part 1 : [101 102 103]
Shape: (3,)
Part 2 : [104 105 106]
Shape: (3,)
Part 3 : [107 108]
Shape: (2,)
Part 4 : [109 110]
Shape: (2,)
Part 5 : [111 112]
Shape: (2,)


TASK-4.
Simulate a WhatsApp group chat: create a 2D NumPy array where each row is a user and each column is the number of messages sent per day for a week. Use np.insert() to add a new user (row) with their message counts, then use np.delete() to remove the user who sent the least messages overall.

In [18]:
messages = np.array([
    [10, 15, 20, 12, 18, 14, 16],  
    [25, 20, 30, 22, 28, 24, 26],  
    [5, 8, 6, 7, 9, 4, 6],         
    [18, 15, 20, 17, 19, 21, 16]    
])

In [19]:
messages

array([[10, 15, 20, 12, 18, 14, 16],
       [25, 20, 30, 22, 28, 24, 26],
       [ 5,  8,  6,  7,  9,  4,  6],
       [18, 15, 20, 17, 19, 21, 16]])

In [21]:
print(" Original WhatsApp Messages:")
print(messages)

 Original WhatsApp Messages:
[[10 15 20 12 18 14 16]
 [25 20 30 22 28 24 26]
 [ 5  8  6  7  9  4  6]
 [18 15 20 17 19 21 16]]


In [22]:
new_user = np.array([[12, 10, 15, 11, 14, 13, 16]])

In [23]:
messages = np.insert(messages, messages.shape[0], new_user, axis=0)

In [24]:
print("After Adding New User:")
print(messages)

After Adding New User:
[[10 15 20 12 18 14 16]
 [25 20 30 22 28 24 26]
 [ 5  8  6  7  9  4  6]
 [18 15 20 17 19 21 16]
 [12 10 15 11 14 13 16]]


In [25]:
total_messages = np.sum(messages, axis=1)

In [26]:
print("Total Messages by Each User:")
print(total_messages)

Total Messages by Each User:
[105 175  45 126  91]


In [27]:
least_user_index = np.argmin(total_messages)

In [28]:
print("User with Least Messages: User", least_user_index + 1)

User with Least Messages: User 3


In [29]:
messages = np.delete(messages, least_user_index, axis=0)

In [30]:

print("After Removing User with Least Messages:")
print(messages)


After Removing User with Least Messages:
[[10 15 20 12 18 14 16]
 [25 20 30 22 28 24 26]
 [18 15 20 17 19 21 16]
 [12 10 15 11 14 13 16]]


TASK-5.
Given a NumPy array of YouTube video view counts, use .view() to create a view and .copy() to create a copy. Modify the first element in each and print all arrays to demonstrate the difference between view and copy.<br><br><em><strong>Hint:</strong> Observe which changes affect the original array.</em>

In [31]:
views = np.array([1000, 2000, 3000, 4000, 5000])

In [32]:
views_view = views.view()
views_copy = views.copy()


In [33]:
views_view[0] = 9999


In [34]:
views_copy[0] = 8888

In [36]:

print("5. view() vs copy()")

print("Original Array:")
print(views)

print("View:")
print(views_view)

print("Copy:")
print(views_copy)

5. view() vs copy()
Original Array:
[9999 2000 3000 4000 5000]
View:
[9999 2000 3000 4000 5000]
Copy:
[8888 2000 3000 4000 5000]
