TASK-1.
Create two NumPy arrays representing the number of likes on your last 7 Instagram posts and your friend's last 7 posts, then use np.add() and np.subtract() to calculate both the combined and difference arrays.

In [1]:
import numpy as np

In [2]:
my_likes = np.array([120, 250, 180, 340, 500, 275, 410])
friend_likes = np.array([150, 220, 200, 300, 450, 310, 390])

In [3]:
my_likes

array([120, 250, 180, 340, 500, 275, 410])

In [4]:
friend_likes

array([150, 220, 200, 300, 450, 310, 390])

In [5]:
combined_likes = np.add(my_likes, friend_likes)

In [6]:
combined_likes

array([270, 470, 380, 640, 950, 585, 800])

In [7]:
difference_likes = np.subtract(my_likes, friend_likes)

In [8]:
difference_likes

array([-30,  30, -20,  40,  50, -35,  20])

In [9]:
print("1. Instagram Likes")
print("My Likes:", my_likes)
print("Friend's Likes:", friend_likes)
print("Combined Likes:", combined_likes)
print("Difference:", difference_likes)

1. Instagram Likes
My Likes: [120 250 180 340 500 275 410]
Friend's Likes: [150 220 200 300 450 310 390]
Combined Likes: [270 470 380 640 950 585 800]
Difference: [-30  30 -20  40  50 -35  20]


TASK-2.
Given a NumPy array of item prices from your last Zomato order, use np.multiply() to apply a 10% discount on each item, then use np.sum() to calculate the final bill amount after discount.<br><br><em><strong>Hint:</strong> To apply a 10% discount, multiply each price by 0.9.</em>

In [10]:
prices = np.array([250, 180, 320, 150, 400])

In [11]:
prices

array([250, 180, 320, 150, 400])

In [12]:
discounted_prices = np.multiply(prices, 0.9)

In [13]:
final_bill = np.sum(discounted_prices)

In [14]:

print("2. Zomato Bill")
print("Original Prices:", prices)
print("Prices After 10% Discount:", discounted_prices)
print("Final Bill Amount:", final_bill)

2. Zomato Bill
Original Prices: [250 180 320 150 400]
Prices After 10% Discount: [225. 162. 288. 135. 360.]
Final Bill Amount: 1170.0


TASK-3.
Take a NumPy array of daily step counts for the last 30 days (you can make up the numbers), and use np.mean(), np.median(), np.std(), and np.max() to analyze your fitness stats like a health app would.

In [15]:
steps = np.array([
    5000, 6500, 7000, 4500, 8000,
    6000, 7500, 5500, 6200, 7100,
    4800, 6900, 8200, 7300, 5600,
    6400, 7700, 6800, 5900, 8500,
    5200, 6100, 7900, 7000, 6600,
    5800, 7400, 8100, 6300, 7200
])


In [16]:
steps

array([5000, 6500, 7000, 4500, 8000, 6000, 7500, 5500, 6200, 7100, 4800,
       6900, 8200, 7300, 5600, 6400, 7700, 6800, 5900, 8500, 5200, 6100,
       7900, 7000, 6600, 5800, 7400, 8100, 6300, 7200])

In [17]:
mean_steps = np.mean(steps)
median_steps = np.median(steps)
std_steps = np.std(steps)
max_steps = np.max(steps)

In [18]:
print("\n3. Fitness Statistics")
print("Mean Steps:", mean_steps)
print("Median Steps:", median_steps)
print("Standard Deviation:", std_steps)
print("Maximum Steps:", max_steps)


3. Fitness Statistics
Mean Steps: 6633.333333333333
Median Steps: 6700.0
Standard Deviation: 1043.4983894999018
Maximum Steps: 8500


TASK-4.
Create a NumPy array of 10 random float ratings (between 1 and 5) for a new movie on BookMyShow, then use np.round(), np.floor(), and np.ceil() to show how the rating would appear if rounded to the nearest whole number, always rounded down, and always rounded up.

In [19]:
np.random.seed(42)

In [20]:
ratings = np.random.uniform(1, 5, 10)

In [21]:
print("4. Movie Ratings")
print("Original Ratings:")
print(ratings)

4. Movie Ratings
Original Ratings:
[2.49816048 4.80285723 3.92797577 3.39463394 1.62407456 1.62397808
 1.23233445 4.46470458 3.40446005 3.83229031]


In [22]:
print("Rounded Ratings:")
print(np.round(ratings))

Rounded Ratings:
[2. 5. 4. 3. 2. 2. 1. 4. 3. 4.]


In [23]:
print("Floor Ratings:")
print(np.floor(ratings))

Floor Ratings:
[2. 4. 3. 3. 1. 1. 1. 4. 3. 3.]


In [24]:

print("Ceiling Ratings:")
print(np.ceil(ratings))

Ceiling Ratings:
[3. 5. 4. 4. 2. 2. 2. 5. 4. 4.]


TASK-5.
Use ChatGPT to generate Python code that calculates the percentage of songs you skipped in your last 20 Spotify plays using NumPy arrays and np.percentile(), then run the code and paste your output.<br><br><em><strong>Hint:</strong> Ask ChatGPT for code that finds the 75th percentile of skips in a NumPy array.</em>

In [25]:
skips = np.array([
    1, 0, 1, 0, 0,
    1, 0, 0, 1, 0,
    1, 0, 1, 0, 0,
    0, 1, 0, 0, 1
])

In [26]:
skip_percentage = np.mean(skips) * 100

In [27]:
skip_75th_percentile = np.percentile(skips, 75)

In [28]:
print("5. Spotify Skip Analysis")
print("Skip Data:", skips)
print("Percentage of Songs Skipped:", skip_percentage, "%")
print("75th Percentile of Skips:", skip_75th_percentile)

5. Spotify Skip Analysis
Skip Data: [1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 1]
Percentage of Songs Skipped: 40.0 %
75th Percentile of Skips: 1.0
