TASK-1.
Create two NumPy arrays: one representing the number of likes on your last 7 Instagram posts, and another for the number of comments. Use arithmetic operators to calculate the average engagement (likes + comments) per post and print the result.

In [1]:
import numpy as np

In [2]:

likes = np.array([120, 250, 180, 340, 500, 275, 410])
comments = np.array([10, 25, 15, 30, 45, 20, 35])

In [5]:

comments

array([10, 25, 15, 30, 45, 20, 35])

In [6]:
likes

array([120, 250, 180, 340, 500, 275, 410])

In [7]:
engagement = likes + comments

In [8]:
engagement

array([130, 275, 195, 370, 545, 295, 445])

In [9]:
average_engagement = np.mean(engagement)

In [10]:
print("1. Average Engagement per Post:")
print(average_engagement)

1. Average Engagement per Post:
322.14285714285717


TASK-2.
Given two NumPy arrays: one with the prices of 5 food items on Zomato and another with the corresponding discounts in rupees, use element-wise subtraction to get the final price for each item and display the array.

In [11]:
prices = np.array([250, 180, 320, 150, 400])
discounts = np.array([50, 30, 70, 20, 100])

In [12]:
prices

array([250, 180, 320, 150, 400])

In [13]:
discounts

array([ 50,  30,  70,  20, 100])

In [14]:
final_prices = prices - discounts

In [15]:
print("\n2. Final Zomato Prices:")
print(final_prices)



2. Final Zomato Prices:
[200 150 250 130 300]


TASK-3.
Suppose you have a NumPy array of IPL team scores for 5 matches. Use comparison operators to create a boolean array indicating which matches had scores greater than 180, then print the boolean array.<br><br><em><strong>Hint:</strong> Use the '>' operator directly on the array.</em>

In [17]:
scores = np.array([175, 195, 160, 210, 185])

In [18]:
scores

array([175, 195, 160, 210, 185])

In [19]:
high_scores = scores > 180

In [20]:
high_scores

array([False,  True, False,  True,  True])

In [22]:
print(" Scores Greater Than 180:")
print(high_scores)

 Scores Greater Than 180:
[False  True False  True  True]


TASK-4.
Create two NumPy arrays: one showing whether a user paid via Paytm (1 for paid, 0 for not) and another for PhonePe for 6 transactions. Use np.logical_or() to find out which transactions were paid by either app and print the result.


In [23]:
paytm = np.array([1, 0, 1, 0, 1, 0])
phonepe = np.array([0, 1, 1, 0, 0, 1])

In [24]:
paytm

array([1, 0, 1, 0, 1, 0])

In [25]:

phonepe

array([0, 1, 1, 0, 0, 1])

In [26]:
paid_by_either = np.logical_or(paytm, phonepe)

In [27]:
paid_by_either

array([ True,  True,  True, False,  True,  True])

In [28]:
print("\n4. Paid by Paytm OR PhonePe:")
print(paid_by_either)


4. Paid by Paytm OR PhonePe:
[ True  True  True False  True  True]


TASK-5.
Given a NumPy array of the number of steps you walked each day for a week, use broadcasting to add a bonus of 500 steps to each day's count, then calculate and print the total steps for the week using an aggregate operation.

In [29]:

steps = np.array([5000, 6500, 7000, 4500, 8000, 6000, 7500])

In [30]:
steps

array([5000, 6500, 7000, 4500, 8000, 6000, 7500])

In [31]:
bonus_steps = steps + 500

In [32]:
total_steps = np.sum(bonus_steps)

In [33]:
bonus_steps

array([5500, 7000, 7500, 5000, 8500, 6500, 8000])

In [35]:
total_steps


np.int64(48000)

In [37]:

print(" Steps After 500-Step Bonus:")
print(bonus_steps)

print("Total Steps for the Week:")
print(total_steps)

 Steps After 500-Step Bonus:
[5500 7000 7500 5000 8500 6500 8000]
Total Steps for the Week:
48000
