In [1]:
import numpy as np

TASK-1.
Given a NumPy array of IPL team names with some duplicates, use np.unique() to print a sorted list of all unique team names.

In [2]:
teams = np.array([
    "CSK", "MI", "RCB", "KKR",
    "MI", "CSK", "GT", "RCB",
    "RR", "GT"
])

In [3]:
teams

array(['CSK', 'MI', 'RCB', 'KKR', 'MI', 'CSK', 'GT', 'RCB', 'RR', 'GT'],
      dtype='<U3')

In [4]:
unique_teams = np.unique(teams)

In [5]:
unique_teams

array(['CSK', 'GT', 'KKR', 'MI', 'RCB', 'RR'], dtype='<U3')

In [6]:

print("1. Unique IPL Teams:")
print(unique_teams)

1. Unique IPL Teams:
['CSK' 'GT' 'KKR' 'MI' 'RCB' 'RR']


TASK-2.
Create a NumPy array of Zomato order ratings (with some NaN values), then use np.isnan() to count how many ratings are missing.

In [7]:
ratings = np.array([4.5, 4.2, np.nan, 3.8, np.nan, 4.7, 4.0])

In [8]:
ratings

array([4.5, 4.2, nan, 3.8, nan, 4.7, 4. ])

In [9]:
missing_ratings = np.isnan(ratings)

In [10]:
number_of_missing = np.sum(missing_ratings)


In [12]:
print(" Zomato Ratings:")
print(ratings)
print("Missing Ratings:", number_of_missing)

 Zomato Ratings:
[4.5 4.2 nan 3.8 nan 4.7 4. ]
Missing Ratings: 2


TASK-3.
Given an array of Flipkart product prices, use np.clip() to limit all prices between 100 and 1000, and print the resulting array.<br><br><em><strong>Hint:</strong> Use np.clip(array, 100, 1000).</em>

In [13]:
prices = np.array([50, 150, 450, 800, 1200, 2500, 999])

In [14]:
prices

array([  50,  150,  450,  800, 1200, 2500,  999])

In [15]:
clipped_prices = np.clip(prices, 100, 1000)


In [17]:
clipped_prices = np.clip(prices, 100, 1000)

print(" Original Flipkart Prices:")
print(prices)

print("Prices After np.clip():")
print(clipped_prices)


 Original Flipkart Prices:
[  50  150  450  800 1200 2500  999]
Prices After np.clip():
[ 100  150  450  800 1000 1000  999]


TASK-4.
You have a NumPy array of YouTube video view counts, some of which are NaN or inf. Replace all NaN values with 0, and all inf values with the maximum finite value in the array.

In [18]:
views = np.array([
    1000,
    2500,
    np.nan,
    5000,
    np.inf,
    3000,
    np.nan,
    np.inf
])

In [19]:
finite_values = views[np.isfinite(views)]

In [20]:
finite_values

array([1000., 2500., 5000., 3000.])

In [21]:
max_finite = np.max(finite_values)

In [22]:
max_finite

np.float64(5000.0)

In [23]:
cleaned_views = views.copy()

In [ ]:
cleaned_views

array([1000., 2500.,   nan, 5000.,   inf, 3000.,   nan,   inf])

In [25]:
cleaned_views[np.isnan(cleaned_views)] = 0

In [26]:
cleaned_views[np.isposinf(cleaned_views)] = max_finite

In [27]:
print(" Original YouTube Views:")
print(views)


 Original YouTube Views:
[1000. 2500.   nan 5000.   inf 3000.   nan   inf]


In [28]:
print("Maximum Finite Value:", max_finite)

Maximum Finite Value: 5000.0


In [29]:
print("Cleaned YouTube Views:")
print(cleaned_views)

Cleaned YouTube Views:
[1000. 2500.    0. 5000. 5000. 3000.    0. 5000.]


TASK-5.
Use ChatGPT to generate a Python code snippet that finds the indices of all even numbers in a NumPy array using np.where(), then test the code with your own example array.

In [30]:
numbers = np.array([11, 24, 37, 42, 55, 60, 73, 88, 91, 100])

In [31]:
even_indices = np.where(numbers % 2 == 0)

In [32]:
even_indices = np.where(numbers % 2 == 0)

In [34]:
print(" Numbers:")
print(numbers)

 Numbers:
[ 11  24  37  42  55  60  73  88  91 100]


In [35]:
print("Indices of Even Numbers:")
print(even_indices[0])

Indices of Even Numbers:
[1 3 5 7 9]
