In [2]:
import numpy as np

TASK-1.
Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. Use basic indexing to print the first and last price.

In [3]:
prices = np.array([199, 299, 399, 499, 599])

In [4]:
prices

array([199, 299, 399, 499, 599])

In [5]:
print("1. First Price:", prices[0])


1. First Price: 199


In [6]:
print("Last Price:", prices[-1])

Last Price: 599


TASK-2.
Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).

In [7]:
scores = np.array([
    [45, 60, 72, 55, 80],   
    [50, 65, 70, 60, 75],   
    [30, 55, 68, 72, 85]    
])


In [8]:
scores

array([[45, 60, 72, 55, 80],
       [50, 65, 70, 60, 75],
       [30, 55, 68, 72, 85]])

In [9]:
selected_scores = scores[:, 1:4]

In [10]:
scores[:,1:4]

array([[60, 72, 55],
       [65, 70, 60],
       [55, 68, 72]])

In [11]:
print("2. Scores for Matches 2 to 4:")
print(selected_scores)

2. Scores for Matches 2 to 4:
[[60 72 55]
 [65 70 60]
 [55 68 72]]


TASK-3.
You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). Use negative indexing to print the last three ratings.

In [14]:
ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

In [15]:
ratings

array([4.5, 3.8, 4.2, 2.9, 5. , 3.5])

In [16]:
print("\n3. Last Three Ratings:")
print(ratings[-3:])


3. Last Three Ratings:
[2.9 5.  3.5]


TASK-4.
Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.<br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>

In [17]:
natural_numbers = np.arange(1, 21)

In [18]:
natural_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
every_third = natural_numbers[1::3]

In [20]:
every_third

array([ 2,  5,  8, 11, 14, 17, 20])

In [22]:
print("4. Every 3rd Number Starting from Second Element:")
print(every_third)

4. Every 3rd Number Starting from Second Element:
[ 2  5  8 11 14 17 20]


TASK-5.
Given a NumPy array of Flipkart product prices, use boolean indexing to extract all prices greater than 500. Print the resulting array.

In [23]:
flipkart_prices = np.array([250, 650, 450, 800, 350, 1200, 500, 750])

In [24]:
flipkart_prices

array([ 250,  650,  450,  800,  350, 1200,  500,  750])

In [25]:
expensive_products = flipkart_prices[flipkart_prices > 500]

In [26]:

print("5. Prices Greater Than 500:")
print(expensive_products)


5. Prices Greater Than 500:
[ 650  800 1200  750]


TASK-6.
You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]). Use np.where() to find the indices of all scores above 200 and print these indices.

In [27]:

ipl_scores = np.array([210, 180, 195, 220, 205, 175])

In [28]:
ipl_scores

array([210, 180, 195, 220, 205, 175])

In [29]:
indices = np.where(ipl_scores > 200)

In [30]:

print("\n6. Indices of Scores Above 200:")
print(indices[0])


6. Indices of Scores Above 200:
[0 3 4]
