TASK-1.
Create a NumPy array representing the number of likes on 7 Instagram posts and print its ndim, shape, size, dtype, itemsize, and nbytes properties.

In [2]:
import numpy as np

In [3]:
likes = np.array([120, 250, 180, 340, 500, 275, 410])

In [4]:
likes

array([120, 250, 180, 340, 500, 275, 410])

In [5]:
likes.ndim


1

In [7]:
print("ndim:",likes.ndim)

ndim: 1


In [8]:
print("shape:", likes.shape)

shape: (7,)


In [9]:
print("size:", likes.size)

size: 7


In [10]:
print("dtype:", likes.dtype)

dtype: int64


In [11]:
print("itemsize:", likes.itemsize, "bytes")

itemsize: 8 bytes


In [12]:
print("nbytes:", likes.nbytes, "bytes")

nbytes: 56 bytes


TASK-2.
Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening), use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.<br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>

In [15]:

steps = n = np.random.randint(10,100,10).reshape(5,2)

In [16]:
steps

array([[64, 86],
       [66, 97],
       [32, 49],
       [46, 59],
       [84, 17]], dtype=int32)

In [17]:
steps = np.array([
    [3500, 4200],   
    [4000, 5000],  
    [3200, 4500],   
    [5000, 5500],   
    [4500, 4800] 
])

print("\n2. Original 2D Steps Array:")
print(steps)
print("Shape:", steps.shape)


2. Original 2D Steps Array:
[[3500 4200]
 [4000 5000]
 [3200 4500]
 [5000 5500]
 [4500 4800]]
Shape: (5, 2)


In [ ]:
# Convert 2D array into 1D
steps_1d = steps.reshape(-1)

print("After converting to 1D:")
print(steps_1d)
print("Shape:", steps_1d.shape)


After converting to 1D:
[3500 4200 4000 5000 3200 4500 5000 5500 4500 4800]
Shape: (10,)


In [19]:

# Convert 1D array back to 2D with 5 rows and 2 columns
steps_2d = steps_1d.reshape(5, 2)

print("After converting back to 2D:")
print(steps_2d)
print("Shape:", steps_2d.shape)

After converting back to 2D:
[[3500 4200]
 [4000 5000]
 [3200 4500]
 [5000 5500]
 [4500 4800]]
Shape: (5, 2)


TASK-3.
Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), flatten(), and resize() to create different shaped versions of the data and print each result.<br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code comments.</em>

In [20]:

prices = np.array([
    120, 150, 80, 200,
    99, 180, 250, 75,
    130, 160, 90, 220
])

print("\n3. Original Food Prices:")
print(prices)
print("Shape:", prices.shape)


3. Original Food Prices:
[120 150  80 200  99 180 250  75 130 160  90 220]
Shape: (12,)


In [21]:
prices_2d = prices.reshape(3, 4)

print(prices_2d)

[[120 150  80 200]
 [ 99 180 250  75]
 [130 160  90 220]]


In [22]:
prices_ravel = prices_2d.ravel()

print(prices_ravel)

[120 150  80 200  99 180 250  75 130 160  90 220]


In [23]:
prices_flatten = prices_2d.flatten()

print(prices_flatten)

[120 150  80 200  99 180 250  75 130 160  90 220]


In [24]:
prices_resize = prices_2d.copy()
prices_resize.resize(4, 3)


In [25]:
print("Using resize() - 4x3:")
print(prices_resize)
print("Shape:", prices_resize.shape)

Using resize() - 4x3:
[[120 150  80]
 [200  99 180]
 [250  75 130]
 [160  90 220]]
Shape: (4, 3)


TASK-4.
Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, then print the transposed array.

In [26]:
playlist = np.array([
    [20, 15, 10],   
    [30, 20, 15],   
    [25, 18, 12]    
])


In [27]:
playlist

array([[20, 15, 10],
       [30, 20, 15],
       [25, 18, 12]])

In [ ]:
playlist_T = playlist.T

print("Using T:")
print(playlist_T)


Using T:
[[20 30 25]
 [15 20 18]
 [10 15 12]]


In [29]:
playlist.T

array([[20, 30, 25],
       [15, 20, 18],
       [10, 15, 12]])

In [30]:
playlist_transpose = np.transpose(playlist)

print("Using np.transpose():")
print(playlist_transpose)


Using np.transpose():
[[20 30 25]
 [15 20 18]
 [10 15 12]]


In [31]:
np.transpose(playlist)

array([[20, 30, 25],
       [15, 20, 18],
       [10, 15, 12]])

TASK-5.
Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() versus ravel() in real projects.

In [32]:
ratings = np.array([
    5, 4, 3, 5, 4,
    2, 5, 3, 4, 5,
    4, 3, 5, 2, 4
])

In [33]:
ratings

array([5, 4, 3, 5, 4, 2, 5, 3, 4, 5, 4, 3, 5, 2, 4])

In [35]:
ratings.shape

(15,)

In [36]:
# Convert 1D array into 3x5
ratings_2d = ratings.reshape(3, 5)

In [37]:
ratings_2d

array([[5, 4, 3, 5, 4],
       [2, 5, 3, 4, 5],
       [4, 3, 5, 2, 4]])

In [38]:
print("Shape:", ratings_2d.shape)

Shape: (3, 5)


In [40]:
ratings_1d = ratings_2d.flatten()

print("After flatten():")
print(ratings_1d)
print("Shape:", ratings_1d.shape)

After flatten():
[5 4 3 5 4 2 5 3 4 5 4 3 5 2 4]
Shape: (15,)


In [41]:
#If you only need to read/process the flattened data and memory efficiency matters, ravel() is often useful. If you need an independent array that can be modified safely without affecting the original, use flatten().